version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    ignore:
      - dependency-name: "org.jbehave:jbehave-core"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: monthly
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 20
